let businesses = [
	'Antiques Dealer',
	'Art Gallery',
	'Bartending Service',
	'Boat Tours',
	'Cake Making',
	'Clothing Boutique',
	'Clothing Line',
	'Clown Service',
	'Coin or Stamp Dealer',
	'Coffee Bar/Tea Salon',
	'Cookie',
	'Craft Beer Pub',
	'Creative Arts Day Camp',
	'Cupcake',
	'Garden Center',
	'Gift-Basket Design',
	'Golf Coach',
	'Gourmet Candy Cart',
	'Hot Air Balloon Rides',
	'Ice Cream Shop',
	'Import/Export',
	'Jewelry Designer',
	'Knitting/Crocheting Lessons',
	'Logo Design',
	'Martini Bar',
	'Miniature Golf Course',
	'Mobile DJ',
	'Night Club Promoter',
	'Outdoor Adventures',
	'Personal Trainer',
	'Rare Book Dealer/Search Service',
	'Sport Fishing Charter Boat',
	'Vintage Toy Producer',
	'Wine Bar',
	'Basement Remodeler',
	'Carpet/Upholstery Cleaning',
	'Craft Classes',
	'Dance Instructor',
	'Day Care Service',
	'Event Organizing',
	'Freelance Writer',
	'Financial Planner',
	'Gardening Consultant',
	'Home Bakery',
	'Home Inspection',
	'Home Landscaping',
	'House Cleaning',
	'Interior Decorating',
	'Local Marketing Service',
	'Manufacturer’s Representative',
	'Music Teaching',
	'Pet Sitting',
	'Photography',
	'Promotional Material',
	'Room Rental',
	'Sales Trainer',
	'Soap and Lotion Making',
	'Sports Coaching and Training',
	'Virtual Assistant',
	'Art Lessons',
	'Bicycle Repair',
	'Car Resale',
	'Career Counselor',
	'Cooking Class Instructor',
	'Collectibles Trading',
	'Craft',
	'Custom Embroidery',
	'Editing Service',
	'Errand Service',
	'Family History Writer (Genealogical Service)',
	'Financial Aid Consultant',
	'Flea Market Vendor',
	'Floating Art Gallery',
	'Grants-Proposal Writer',
	'Graphic Designer',
	'Gutter Cleaner',
	'Hat Making',
	'Interior Room Painting/Wallpapering',
	'Life Coaching',
	'Party Planner',
	'Personal Shopping Service',
	'Scrapbooking',
	'Speaking and Presentation Coaching',
	'Test Prep Coach',
	'Used Boat Sales',
	'Yard Sales',
	'Antique Refurbishment',
	'Arbitration Service',
	'Art Restoration Services',
	'Art-Buying Consultant',
	'Baby Proofing Service',
	'Bicycle Rentals',
	'Book Packager',
	'Bookkeeping',
	'Boudoir Photography',
	'Business Broker',
	'Carpet Installation',
	'Catering Service',
	'Furniture Making',
	'House Painting',
	'Human Resources Service',
	'Image Consultant',
	'Irrigation Services',
	'Makeup Consulting',
	'Map Publisher/Distributor',
	'Messenger Service',
	'Mobile Hair Salon',
	'Nursery Design Service',
	'Personal Computer Training',
	'Pet Taxi Service',
	'Publicity',
	'Smartphone Repair',
	'Stair Lift',
	'Vintage Clothing',
	'Affiliate Marketing',
	'App Creator',
	'Content Marketing',
	'Domain Name Trading',
	'Dropship',
	'eBay Selling',
	'eBook Publishing',
	'E-commerce',
	'Fashion blog',
	'Internet Marketing Specialist',
	'Internet Researcher',
	'Lead Generator for Locales',
	'Local Interest Blog',
	'Online Game',
	'Podcasting',
	'Product Reviewer',
	'Resume Writing',
	'Sell on Etsy',
	'SEO Specialist',
	'Social Media Influencer',
	'Social Media Specialist',
	'UI/UX Design',
	'Virtual Consignment Store',
	'Website Developer',
	'Advertising Agency',
	'Air Charter Service',
	'Apartment Building Owner',
	'Automotive Parts Rebuilder',
	'Banquet Facility',
	'Beer Brewery',
	'Car Wash',
	'Commercial Real Estate Broker',
	'Concert Promoter',
	'Corporate Insurance Broker',
	'Damage Restoration Service',
	'Day Spa',
	'Demolition/Wrecking Contractor',
	'Executive Search Firm',
	'Fitness Rental Equipment',
	'Fund-Raising Firm',
	'Health Club',
	'Home Health Care Service',
	'Liquidator',
	'Meal Preparation Service',
	'Mobile Billboard Service',
	'Money Broker',
	'Musical Instrument Leasing',
	'Nanny Service',
	'Outplacement Service',
	'Porta Potty Rental',
	'Prefab Home Sales/Construction',
	'Real Estate Investor',
	'Rehabbing Houses',
	'Residence for the Elderly',
	'Restaurant',
	'Security',
	'Senior Care',
	'Shipping/Freight Forwarding Service',
	'Temporary Employment Agency',
	'Tree Service',
	'Used Car Leasing',
	'Used Industrial Equipment Sales',
	'Venture Capitalist',
	'Wedding Venue',
	'Weight Loss Center',
	'Window Treatment Specialist',
	'Alterations/Seamstress',
	'Aquarium Maintenance',
	'Association Management Service',
	'Boat Maintenance/Cleaning Service',
	'Building Maintenance Service',
	'Coin-Operated Laundry',
	'Commercial Plant-Watering Service',
	'Employee Leasing',
	'Fabric Coverings',
	'Jewelry/Clock/Watch Repair',
	'Lawn Service',
	'Locksmith',
	'Mobile Car Inspection/Repair',
	'Office Cleaning',
	'Pest Control Service',
	'Pet Grooming',
	'Pool Maintenance and Cleaning',
	'Property Management Service',
	'Sandwich Shop',
	'Spa Service',
	'Storage Service',
	'Tailoring Service',
	'Television Repair',
	'Uniform Service',
	'Vending Machine Owner',
	'Apartment Preparation Service',
	'Baby-Sitting Service',
	'Balloon Delivery Service',
	'Boat Operation Instructor',
	'Bridal Consultant',
	'Bulletin Board Service',
	'Business Plan Writer',
	'Chef for Hire',
	'Cosmetic Sales',
	'Decks/Outdoor Furniture',
	'Dog Walking Service',
	'Firewood Service',
	'Garage Clean Out and Trick Out',
	'Hauling Service',
	'Home Entertainment System Service',
	'Home Office Consultant',
	'Home Tutoring',
	'House Cleaning',
	'Leaflet distributing',
	'Mobile Auto Washing',
	'Moving Service',
	'Personal Concierge',
	'Professional Organizer',
	'T-Shirt',
	'Walking Tour',
	'Window Washing Service',
	'Yoga Classes',
	'3D Printing',
	'All-Day Breakfast Restaurant',
	'Arcade/Party Rentals',
	'Audiobook Producer/Distributor',
	'Bed &amp; Breakfast',
	'Bridal Show Promotions',
	'Café',
	'Canoe Livery',
	'Cataloging Art Collections',
	'Child Development Center',
	'Cigar Shop',
	'Collection Agency',
	'Construction Service',
	'Consultant on Foreign Cultures',
	'Dog Trainer',
	'Doggie Bed and Breakfast',
	'Drone',
	'Dry Cleaning',
	'Electrical Contractor/Electrician',
	'Fence Installation Service',
	'Flea Market Organizer',
	'Floral Shop',
	'Food Delivery Service',
	'Food Truck or Food Cart',
	'Formal Wear Rental Service',
	'Framing Service',
	'Gift Show Organizer',
	'Golf Driving Range',
	'Home Staging',
	'Horse/Cargo Trailer Service',
	'Instant Signs',
	'Invisible Fencing Sales and Installation',
	'Jet Ski Rentals',
	'Key Control Systems',
	'Mailbox Rental Service',
	'Massage Therapist',
	'Meeting Planner',
	'Motivational Speaker',
	'Murder Mystery Producer',
	'Nail Studio',
	'Non-profit',
	'Nutritionist Consulting',
	'Personalization',
	'Pilot/Flying Lessons',
	'Pizza Delivery',
	'Power Wash Service',
	'Real Estate Appraiser',
	'Resale Shop',
	'Specialty Food Store',
	'Smoothies',
	'Snow Plow Service',
	'Sports Equipment Sales/Service',
	'Tow Boat Operator',
	'Trophy/Engraving Service',
	'Vacuum Cleaner Repair',
	'Video Production Company',
	'Winery'
];