let themes = [
    'Modern',
    '1990\'s Inspired',
    'Vintage',
    'Clean',
    'Coloful',
    'Rustic',
    'Glamorous',
    'Exotic',
    'Functional',
    'Joyful',
    'Strong',
    'Fiery',
    'Medieval',
    'Steam Punk',
    'Flat',
    'Hip',
    'Trendy',
    'Simple',
]